services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: fraud_db
      POSTGRES_DB: fraud_db
      POSTGRES_PASSWORD: fraud_db
    volumes: 
      - fraud-db:/var/lib/postgresql
    ports:
      - '5433:5432'

  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  fraud-db: